services:
    web:
        image: nginx:latest
        ports:
            - "6080:6080"
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-fpm

    php-fpm:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html

    db:
        build:
            context: .
            dockerfile: mysql/Dockerfile
        ports:
            - "5306:5306"
        volumes:
            - .:/var/www/html/mysql
        environment:
            MYSQL_ROOT_PASSWORD: attendance@2024!
            MYSQL_DATABASE: attendance
            MYSQL_USER: ictudev
            MYSQL_PASSWORD: attendance@2024!

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "5080:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: attendance@2024!
