version: '3'

networks:
  laravel:
  traefik:

services:
  traefik:
    image: traefik:v2.5
    container_name: traefik
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - laravel
      - traefik

  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    container_name: nginx
    ports:
      - "7080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx-prod/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`attendance.antiquespride.dev`)"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: attendance
      MYSQL_USER: ictudev
      MYSQL_PASSWORD: attendance@2024!
      MYSQL_ROOT_PASSWORD: attendance@2024!
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    ports:
      - "9001:9000"
    networks:
      - laravel
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php.rule=Host(`ws.ictudev.tech`)"
      - "traefik.http.services.php.loadbalancer.server.port=8080"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: attendance@2024!
    ports:
      - "8181:80"
    networks:
      - laravel

  supervisord:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: supervisord
    restart: unless-stopped
    entrypoint: ['/usr/local/bin/entrypoint.sh']
    volumes:
      - ./src:/var/www/html
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    depends_on:
      - php
    networks:
      - laravel
    command: >
      sh -c "php /var/www/html/artisan reverb:start --host=0.0.0.0 --port=7080 --scheme=http"