
version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx-prod/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:lts-oracle
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    environment:
      MYSQL_DATABASE: attendance
      MYSQL_USER: ictudev
      MYSQL_PASSWORD: attendance@2024!
      MYSQL_ROOT_PASSWORD: attendance@2024!
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    ports:
      - "9001:9000"
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: attendance@2024!
    ports:
      - "8181:80"
    networks:
      - laravel


  supervisord:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: supervisord
    restart: unless-stopped
    entrypoint: ['/usr/local/bin/entrypoint.sh']
    volumes:
      - ./src:/var/www/html
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    depends_on:
      - php
    networks:
      - laravel
