
version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx-prod/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    ports:
      - "9001:9000"
    networks:
      - laravel

  
  supervisord:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: supervisord
    restart: unless-stopped
    entrypoint: ['/usr/local/bin/entrypoint.sh']
    volumes:
      - ./src:/var/www/html
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    depends_on:
      - php
    networks:
      - laravel

  
  reverb:
    build:
        context: .
        dockerfile: reverb/Dockerfile
    container_name: reverb
    ports:
        - 4080:80
    volumes:
        - ./src:/var/www/html
    networks:
        - laravel
    depends_on:
        - php
